server.port=8081
spring.application.name=site1-employees

# URL of Site 2 — change if running on different host
site2.url=http://localhost:8082

# Increase max response size for transferring 10k employee records
spring.mvc.async.request-timeout=60000
